require:
  - standard/cop/block_single_line_braces
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - "bin/*"
  TargetRubyVersion: 3.0
  NewCops: enable

############### Layout ###############

Layout/LineLength:
  Max: 120

############### Style ###############

Style/FrozenStringLiteralComment:
  Enabled: true

############### Style ###############

RSpec/DescribeClass:
  IgnoredMetadata:
    type:
      - task

RSpec/ExampleLength:
  Enabled: false
