name: docs

on:
  push:
    branches:
    - master
    paths:
    - "**/*.md"
  pull_request:
    paths:
    - "**/*.md"

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Lint Markdown files with RuboCop
        run: |
          gem install bundler
          bundle install --gemfile gemfiles/rubocop.gemfile --jobs 4 --retry 3
          bundle exec --gemfile gemfiles/rubocop.gemfile rubocop -c .rubocop-md.yml --parallel
